language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '10'
  - '9'
  - '8'
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
script:
  - yarn test
  - yarn build
before_deploy:
  - yarn build:docs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: .docs/dist
  on:
    branch: master
