language: node_js
cache: yarn
node_js:
  - '10'
script:
  - yarn test
  - yarn build
  - yarn build:docs
after_success:
  - yarn travis-deploy-once "npm run semantic-release"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: .docs/dist
  on:
    branch: master
