language: node_js
cache: yarn
node_js:
  - '10'

jobs:
  include:
    - stage: test
      script:
        - yarn test
        - yarn lint
    - stage: build
      script:
        - yarn build
        - yarn build:docs
    - stage: release
      script:
        - yarn semantic-release
    - stage: deploy
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        keep_history: true
        local_dir: .docz/dist
        on:
          branch: master
