name: Non-master

on:
  push:
    branches-ignore: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - name: Run tests
      run: |
        yarn test
        yarn lint
